# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
    gradle(task: "connectedAndroidTest")
  end

  desc "Submit a new Beta Build to Firebase App Distribution"
  lane :uat do
    gradle(
      task: "assemble",
      flavor: "Uat",
      build_type: "Release",
      print_command: false,
      properties: {
        "versionCode" => 1,
        "versionName" => "1.0.0",
        "android.injected.signing.store.file" => "/Users/weiyi.li/Develop/hello_fastlane/keystore/hello_fastlane_release.keystore",
        "android.injected.signing.store.password" => ENV["HELLO_FASTLANE_STORE_PASSWORD"],
        "android.injected.signing.key.alias" => ENV["HELLO_FASTLANE_KEY_ALIAS"],
        "android.injected.signing.key.password" => ENV["HELLO_FASTLANE_KEY_PASSWORD"],
      }
    )
    firebase_app_distribution(
        app: "1:248056200310:android:a95d87ffbabbc46ca1b357",
        testers: "weiyi.just2@gmail.com",
        release_notes: "Test for releasing App to Firebase by Fastlane",
    )
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end
end
